name: fidbak
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth:
  cloud_firestore:
  flutter_spinkit: "^4.1.1"
  fluttertoast: ^3.1.3
  awesome_dialog:
  progress_dialog: ^1.2.1
  qr_flutter: ^3.1.0
  path_provider: any
  image_gallery_saver: ^1.2.2
  permission_handler:
  image_picker_saver: ^0.3.0
  share_extend: ^1.1.2
  share_it: ^0.5.1+3
  shared_preferences: ^0.5.6+3
  qr_code_scanner: 0.0.12
  material_design_icons_flutter: 4.0.5045
  flutter_speed_dial: ^1.2.5
  flare_splash_screen: ^3.0.1
  flutter_fluid_slider: ^1.0.2
  grouped_buttons: ^1.0.4
  reviews_slider: "^1.0.4"
  charts_flutter: ^0.9.0
  cupertino_icons: ^0.1.3
  file_picker: ^1.7.1
  excel: ^1.0.7
  path: ^1.7.0


flutter:
  uses-material-design: true
  assets:
    - assets/

module:
  androidX: true